# Generated by Django 4.2.7 on 2023-11-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getform',
            name='date',
            field=models.DateField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='getform',
            name='email',
            field=models.EmailField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='getform',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='getform',
            name='text',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
