# Generated by Django 4.2.7 on 2023-11-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_form', '0002_alter_getform_date_alter_getform_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getform',
            name='date',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='getform',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getform',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='getform',
            name='text',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
